# Copyright 2026 Esri
#
# Licensed under the Apache License Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: notebook-server-linux-azure-image

on: 
  workflow_dispatch:

env:
  ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_USE_AZUREAD: true
  AZURE_DEFAULT_REGION: ${{ vars.AZURE_DEFAULT_REGION }}
  ARCGIS_ONLINE_USERNAME: ${{ secrets.ARCGIS_ONLINE_USERNAME }}
  ARCGIS_ONLINE_PASSWORD: ${{ secrets.ARCGIS_ONLINE_PASSWORD }}
  PYTHONPATH: ${{ github.workspace }}/azure/scripts
  CONFIG_FILE: ${{ github.workspace }}/config/azure/arcgis-notebook-server-linux/image.vars.json

concurrency:
  group: ${{ github.ref_name }}
  
jobs:
  image:
    name: Build Images
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: azure/arcgis-notebook-server-linux/image
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Azure SDK for Python
        id: install-azure-sdk
        run: pip install azure-identity azure-keyvault-secrets azure-mgmt-compute azure-storage-blob
      - name: Create VM Image Definition
        run: |
          az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID --output none
          az account set --subscription $ARM_SUBSCRIPTION_ID
          ENTERPRISE_ID=$(jq -r '.enterprise_id' $CONFIG_FILE)
          DEPLOYMENT_ID=$(jq -r '.deployment_id' $CONFIG_FILE)
          ARCGIS_VERSION=$(jq -r '.arcgis_version' $CONFIG_FILE)
          OS=$(jq -r '.os' $CONFIG_FILE)
          VAULT_NAME=$(az keyvault list --query "[?tags.ArcGISEnterpriseID=='$ENTERPRISE_ID' && tags.ArcGISRole=='enterprise-vault'].name" -o tsv)
          IMAGE_GALLERY_NAME=$(az keyvault secret show --name "image-gallery-name" --vault-name "$VAULT_NAME" --query "value" -o tsv)
          az sig image-definition create --resource-group $ENTERPRISE_ID-infrastructure-core --gallery-name $IMAGE_GALLERY_NAME \
            --gallery-image-definition $DEPLOYMENT_ID-$ARCGIS_VERSION-$OS \
            --publisher $ENTERPRISE_ID --offer $DEPLOYMENT_ID --sku $ARCGIS_VERSION-$OS \
            --description "ArcGIS Notebook Server $ARCGIS_VERSION images for $OS" \
            --os-type Linux --os-state Generalized --architecture x64 --hyper-v-generation V2 \
            --features SecurityType=TrustedLaunch \
            --minimum-cpu-core 4 --minimum-memory 16384
      - uses: hashicorp/setup-packer@v3
        with:
          version: "1.14.1"
      - name: Run Packer
        id: packer
        run: |
          ENTERPRISE_ID=$(jq -r '.enterprise_id' $CONFIG_FILE)
          VAULT_NAME=$(az keyvault list --query "[?tags.ArcGISEnterpriseID=='$ENTERPRISE_ID' && tags.ArcGISRole=='enterprise-vault'].name" -o tsv)
          packer init .
          packer build -var-file=$CONFIG_FILE -var "vault_name=$VAULT_NAME" .
