# Copyright 2025 Esri
#
# Licensed under the Apache License Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: site-automation-chef-azure-destroy

on: 
  workflow_dispatch:

env:
  TF_VAR_azure_region: ${{ vars.AZURE_DEFAULT_REGION }}
  ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_USE_AZUREAD: true
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  TERRAFORM_BACKEND_STORAGE_ACCOUNT_NAME: ${{ vars.TERRAFORM_BACKEND_STORAGE_ACCOUNT_NAME }}
  TERRAFORM_BACKEND_CONTAINER_NAME: ${{ vars.TERRAFORM_BACKEND_CONTAINER_NAME }}
  ARCGIS_ONLINE_USERNAME: ${{ secrets.ARCGIS_ONLINE_USERNAME }}
  ARCGIS_ONLINE_PASSWORD: ${{ secrets.ARCGIS_ONLINE_PASSWORD }}
  PYTHONPATH: ${{ github.workspace }}/azure/scripts
  CONFIG_FILE: ${{ github.workspace }}/config/azure/arcgis-site-core/automation-chef.tfvars.json

concurrency:
  group: ${{ github.ref_name }}

jobs:
  destroy:
    name: Chef Automation 
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: azure/arcgis-site-core/automation-chef
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.10.0"
    - name: Azure SDK for Python
      id: install-azure-sdk
      run: pip install azure-identity azure-storage-blob
    - name: Terraform Destroy
      id: terraform-destroy
      run: |
        SITE_ID=$(jq -r '.site_id' $CONFIG_FILE)
        terraform init -backend-config="storage_account_name=$TERRAFORM_BACKEND_STORAGE_ACCOUNT_NAME" \
            -backend-config="container_name=$TERRAFORM_BACKEND_CONTAINER_NAME" \
            -backend-config="key=$SITE_ID/azure/automation-chef.tfstate"
        terraform destroy -var-file $CONFIG_FILE -auto-approve
