name: enterprise-k8s-aws-image

on: 
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
  AWS_MAX_ATTEMPTS: 400
  # CONTAINER_REGISTRY: 'docker.io/esridocker'
  CONTAINER_REGISTRY_ORG: 'esridocker'
  CONTAINER_REGISTRY_USER: ${{ secrets.CONTAINER_REGISTRY_USER }}
  CONTAINER_REGISTRY_PASSWORD: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
  CONFIG_FILE: ${{ github.workspace }}/config/aws/arcgis-enterprise-k8s/organization.tfvars.json

concurrency:
  group: ${{ github.ref_name }}
  
jobs:
  image:
    name: Copy Container Images to Amazon ECR
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: aws/arcgis-enterprise-k8s/image
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      - name: Clean up space
        run: |
          # Clean up space for the image copy
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          docker rmi node:16 node:18 node:20 > /dev/null 2>&1
      - name: Copy images to ECR
        run: |
          ARCGIS_VERSION=$(jq -r '.arcgis_version' $CONFIG_FILE)
          echo "ArcGIS Enterprise version: $ARCGIS_VERSION"
          MANIFEST_PATH=./manifests/$ARCGIS_VERSION.dat
          # Run the image copy script
          chmod +x ./image-copy-ecr.sh
          ./image-copy-ecr.sh $MANIFEST_PATH
