---
# Copyright 2024 Esri
#
# Licensed under the Apache License Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This playbook unregisters all Web Adaptors from the ArcGIS Server site.

- name: Unregister Web Adaptors
  hosts: all
  tasks:
    - name: Unregister Web Adaptors
      vars:
        ansible_aws_ssm_timeout: 3600
      no_log: false
      ignore_errors: yes
      arcgis.server.unregister_web_adaptors:
        server_url: 'https://localhost:6443/arcgis'
        admin_username: '{{ admin_username }}'
        admin_password: '{{ admin_password }}'
